Feature/aodv receiver
btcven/RIOT pull request #12
Opened 2020-02-12 07:41 UTC by gustavosinbandera1

This PR is in order to handle reception of packets with rfc5444 format

2020-02-12 12:57 UTC, jeandudey requested changes
Some changes required.

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/aodvv2.h
> +void aodv_set_metric_type(aodvv2_metric_t metric_type);
```suggestion
void gnrc_aodvv2_set_metric_type(aodvv2_metric_t metric_type);
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +
This can be removed.

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> + *
```suggestion
 * Copyright (C) 2020 Locha Inc
 *
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> + */
```suggestion
 * @author      Gustavo Grisales <email@domain.gtld>
 */
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +  HOP_COUNT = 3, /**< see RFC6551*/
Nit:
```suggestion
    HOP_COUNT = 3, /**< see RFC 6551 */
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +  RFC5444_MSGTYPE_RREQ = 10,
```suggestion
  RFC5444_MSGTYPE_RREQ = 10, /**< RREQ message type */
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +  RFC5444_MSGTYPE_RREP = 11,
```suggestion
  RFC5444_MSGTYPE_RREP = 11, /**< RREP message type */
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +  RFC5444_MSGTYPE_RERR = 12,
```suggestion
  RFC5444_MSGTYPE_RERR = 12, /**< RERR message type */
```

2020-02-12 12:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +  RFC5444_MSGTLV_METRIC,
Add documentation.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.h
> +
Remove please.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/constants.h
> +
Remove please.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/reader.c
> +#endif
You can remove this macro and use only the `DEBUG` macro.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/reader.c
> +#define VERBOSE_DEBUG (1)
Can be removed.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/reader.h
> + * @author Gustavo Grisales <gustavosinbandera1@hotmail.com>
Indent correctly.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/utils.h
> + */
Remove please.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/writer.c
> +
Remove please.

2020-02-12 12:57 UTC, jeandudey commented on sys/net/gnrc/aodvv2/writer.h
> +
Remove please.

2020-02-12 16:58 UTC, luisan00 requested changes
Please review 🍡

2020-02-12 16:58 UTC, luisan00 commented on sys/include/net/gnrc/aodvv2/aodvv2.h
> +
Delete this block

2020-02-12 16:58 UTC, luisan00 commented on sys/net/gnrc/aodvv2/aodv.c
> +
Delete this block

2020-02-12 16:58 UTC, luisan00 commented on sys/include/net/gnrc/aodvv2/types.h
> +                               *   successfully parsed. */
Use inline the formula `/* */` for comments please

2020-02-12 16:58 UTC, luisan00 commented on sys/net/gnrc/aodvv2/aodv.h
> +                                           *   or RREP should be sent */
Use the inline `/*  */` formula

2020-02-12 16:58 UTC, luisan00 commented on sys/net/gnrc/aodvv2/aodv.h
> +                             *   should be sent */
Use the inline `/*  */` formula

2020-02-12 16:58 UTC, luisan00 commented on sys/net/gnrc/aodvv2/writer.c
> +
remove empty lines

2020-02-12 16:58 UTC, luisan00 commented on sys/net/gnrc/aodvv2/writer.c
> +    // /* set address to which the write_packet callback should send our RREQ */
use the correct formula for to comment this, please

2020-02-12 18:29 UTC, jeandudey requested changes

2020-02-12 18:29 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/aodvv2.h
> +void gnrc_aodv_set_metric_type(aodvv2_metric_t metric_type);
```suggestion
void gnrc_aodvv2_set_metric_type(aodvv2_metric_t metric_type);
```

2020-02-12 18:29 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
>  #include <timex.h> //yo---
```suggestion
#include <timex.h>
```

2020-02-12 18:29 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +    /**
```suggestion
/**
```

2020-02-12 18:29 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/types.h
> +    } aodvv2_metric_t;
Fix indentation.

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.c
> +/* Copyright (C) 2020 Locha Inc
Put it down.

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.c
> +        DEBUG("<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>ESTO ES UN ROUTE REQUEST\n");
```suggestion
        DEBUG("[_write_packet]: this is a RREQ.\n");
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.c
> +    sock_udp_ep_t remote = {.family = AF_INET6};
```suggestion
    sock_udp_ep_t remote = {
        .family = AF_INET6,
        .port = MANET_PORT,
    };
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.c
> +    remote.port = MANET_PORT;
```suggestion
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.c
> +        if ((res = recvfrom(_socket, buf_rcv, sizeof(buf_rcv), 0,
Use `gnrc_sock_udp` API for this

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/aodv.h
> + * @file        aodvv2/types.h
```suggestion
 * @file        types.h
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/seqnum.c
> + * @file        aodvv2/types.h
```suggestion
 * @file        seqnum.c
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/seqnum.c
> + * @brief       data types for the aodvv2 routing protocol
```suggestion
 * @brief       AODVv2 sequence number
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/utils.c
> + * @file        aodvv2/types.h
```suggestion
 * @file        utils.c
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/utils.h
> + * @file        aodvv2/types.h
```suggestion
 * @file        utils.h
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/writer.h
> + * @file        aodvv2/types.h
```suggestion
 * @file        writer.c
```

2020-02-12 18:29 UTC, jeandudey commented on sys/net/gnrc/aodvv2/writer.h
> + * @brief       data types for the aodvv2 routing protocol
```suggestion
 * @brief       Writer to create RFC 5444 AODVv2 messages
```

2020-02-12 18:57 UTC, jeandudey commented on sys/include/net/gnrc/aodvv2/aodvv2.h
> +void gnrc_aodv_set_metric_type(aodvv2_metric_t metric_type);
@gustavosinbandera1 not done yet.

2020-02-12 22:25 UTC, luisan00 requested changes
🍔

2020-02-12 22:25 UTC, luisan00 commented on sys/include/net/gnrc/aodvv2/types.h
> + * @author      Gustavo Grisales <gustavosinbandera1@hotmail.com.com>
change gustavosinbandera1@hotmail.com.com to gustavosinbandera1@hotmail.com

2020-02-12 22:25 UTC, luisan00 commented on sys/net/gnrc/aodvv2/aodv.c
> + * @author      Gustavo Grisales <gustavosinbandera1@hotmail.com.com>
change gustavosinbandera1@hotmail.com.com to gustavosinbandera1@hotmail.com

2020-02-12 22:25 UTC, luisan00 commented on sys/net/gnrc/aodvv2/aodv.c
> +                                                                                return ipv6_addr;
Fix Indentation

2020-03-20 17:46 UTC, closed without merging

2020-03-20 17:46 UTC, jeandudey commented
This work was merged on btcven/radio-firmware already, with modifications from @gustavosinbandera1 and my person.